api-version: 1.13
author: gyuriX
depend: [ WorldEdit, WRLDPaymentsAPI ]
main: gyurix.playershops.PlayerShopsPlugin
name: PlayerShops
version: 1.0
softdepend: [ Villas ]
commands:
  playershop:
    aliases: [ pshop ]
  playershopa:
    aliases: [ pshopa ]
